config/routes.rb
Rails.application.routes.draw do


  root "home#index"

  # Routes for the home controller
  get 'home/contact'
  get 'home/index'
  get 'home/about'
  get 'home/faq'
  get 'home/custom_report'
  get 'home/activity_sheet'
  post '/report' => "home#custom_report"
  get '/dispose_item/:id' => "home#dispose_item"
  get '/pharmacy_sheet/:date' => "home#activity_sheet"
  get '/provider_suggestions' => "home#provider_suggestions"
  get '/drug_name_suggestions' => "home#drug_name_suggestions"

  # Routes for the sessions controller

  get 'sessions/new'
  get 'sessions/destroy'
  post 'sessions/create'
  get "/login" => "sessions#new"
  get "/logout" => "sessions#destroy"

  # Routes for the general inventory 
  get "general_inventories/print/:id" => "general_inventories#print"
  get "/void_general_inventory/:id" => "general_inventories#delete", as: 'void_general_inventory'
  post "/delete_general_inventory_item/:id" => "general_inventories#destroy"


  # Routes for the pmap inventory 
  get "/reorders" => "pmap_inventories#reorders"
  get "pmap_inventories/print/:id" => "pmap_inventories#print"
  get "/move_pmap_inventory/:id" => "pmap_inventories#move_inventory"
  post "/delete_pmap_inventory_item/:id" => "pmap_inventories#destroy"
  get "/void_pmap_inventory/:id" => "pmap_inventories#delete", as: 'void_pmap_inventory'


  # Routes for prescriptions
  get "void_prescription/:id" => "prescriptions#void_prescription", as: 'void_prescription'
  get "ajax_prescriptions" => "prescriptions#ajax_prescriptions"
  get "dashboard" => "prescriptions#dashboard"

  # Routes for dispensaions
  get "print_dispensation_label" => "dispensations#print_dispensation_label"
  get "/refill" => "dispensations#refill"
  post "/refill" => "dispensations#refill"

  # Routes for users
  get "/new_user_role" => "users#new_user_role"
  post "users/create_user_role", as: 'create_user_role'

  # Routes for patients
  post "/update_language/:id" => "patients#update_language"


  # Routes for manufacturers
  post "/toggle_pmap/:id" => "manufacturers#toggle_pmap"
  get "/void_manufacturer/:id" => "manufacturers#delete", as: 'void_manufacturer'


  # Routes for news
  get "/void_news_item/:id" => "news#delete", as: 'void_news'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :news
  resources :users
  resources :patients
  resources :prescriptions
  resources :dispensations
  resources :manufacturers
  resources :pmap_inventories
  resources :general_inventories
end

app/models/patient.rb
class Patient < ApplicationRecord

    def name
        return "#{self.first_name.to_s} #{self.last_name.to_s}" 
    end

    def full_gender
        case self.gender
        when "F"
            return "Female"
        when "M"
            return "Male"
        else 
            return "Other"
        end
    end

    def formatted_dob
        return self.birthdate.strftime("%B %d, %Y") rescue "Unknown"
    end

    def age
        age_in_days = (Date.today - self.birthdate).to_i

        if age_in_days < 31
            return age_in_days.to_s + " days"
        elsif age_in_days < 365
            years = (Date.today.year - self.birthdate.year)
            months = (Date.today.month - self.birthdate.month)
            return ((years * 12) + months).to_s + " months"
        else
            return (age_in_days / 365)
        end
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
    def index
        if params[:pmap_only].blank?
            @patients = Patient.where(:voided => false)
            @patient_count = @patients.count
            @pmap_patients = PmapInventory.select("distinct patient_id").where(:voided => false).count
        else
            pt_on_pmap = PmapInventory.where(:voided => false).pluck(:patient_id).uniq
            @patients = Patient.where("voided = ?  and patient_id in (?) ", false, pt_on_pmap)
            @patient_count = Patient.where(:voided => false).count
            @pmap_patients = pt_on_pmap.length
        end
    end

    def show
        @patient = Patient.find(params[:id])
        @history = Dispensation.where("patient_id = ? and voided = ?",params[:id],false).order(dispensation_date: :desc).limit(6)
        pmap_items =  PmapInventory.select("manufacturer, rxaui, sum(current_quantity) as current_quantity").where(:patient_id => params[:id],
                                       :voided => false).group(:manufacturer, :rxaui)            
        @pmap_meds = {}
        (pmap_items || []).each do |med|
            @pmap_meds[med.manufactured_by] = [] if @pmap_meds[med.manufactured_by].blank?
            @pmap_meds[med.manufactured_by] << ["#{med.drug_name}", med.current_quantity,med.manufacturer, med.rxaui]
        end
    end

    def new 
    end

    def create
        new_patient = Patient.create(patient_params)
        if new_patient.errors.blank?
            flash[:success] = {title: "Patient Record Created", message: "Record for #{new_patient.name} has been successfully created"}
            redirect_to "/patients/#{new_patient.id}"
        else
            flash[:errors] = {title: "Patient Record Not Created", message: "Record for #{new_patient.name} could not be created"}
            redirect_to "/patients"
        end
    end

    def edit
        @patient = Patient.find(params[:id])
    end

    def update
        patient = Patient.find(params[:id])
        if patient.blank?
            flash[:errors] = {title: "Patient Record Not Updated", message: "Record for could not be found."}
        else
            patient.update(patient_params)
            if patient.errors.blank?
                flash[:success] = {title: "Patient Record Created", message: "Record for #{patient.name} has been successfully updated!"}
            else
                flash[:errors] = {title: "Patient Record Not Updated", message: "Record for #{patient.name} could not be updated."}
            end
        end

        redirect_to "/patients/#{params[:id]}"
    end

    def delete
    end

    def destroy
    end

    def update_language
        patient = Patient.where("patient_id = ? ", params[:id]).update(:language => params[:language])
        status = patient.first.errors.blank? 
        respond_to do |format|
            format.json {render json: status}       
        end
    end

    private
    def patient_params
        params.require(:patient).permit(:voided,:epic_id, :first_name, :last_name, :birthdate, :gender, :language, :address, :city, :state, :zip, :phone)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_edit.html.erb
<%= form_for :patient, :url => "/patients/#{params[:id]}", :method => "PATCH"  do |f| %>
    <div class="card">
        <h5 class="card-header bg-dark text-light">Edit Patient Record</h5>
        <div class="card-body">
            <div class="form-row">
                <div class="col">
                    <label class="col-form-label">First Name</label>
                    <input type="text" class="form-control" name="patient[first_name]" value="<%= @patient.first_name %>" placeholder="First name" required>
                </div>
                <div class="col">
                    <label class="col-form-label">Last Name</label>
                    <input type="text" class="form-control" name="patient[last_name]" value="<%= @patient.last_name %>" placeholder="Last name" required>
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <label class="col-form-label">Gender</label>
                    <select class="form-control" name="patient[gender]" required>
                        <option value="" disabled >&nbsp;</option>
                        <option value="M" >Male</option>
                        <option value="F" >Female</option>
                        <option value="O" >Other</option>
                    </select>
                </div>
                <div class="col">
                    <label class="col-form-label">Birthdate</label>
                    <input type="date" class="form-control" name="patient[birthdate]" value="<%= @patient.birthdate %>" placeholder="Date of Birth" required>
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <label class="col-form-label">MRN</label>
                    <input type="text" class="form-control" name="patient[epic_id]" value="<%= @patient.epic_id %>" placeholder="Enter Chart Number" required>
                </div>
                <div class="col">
                    <label class="col-form-label">Preferred Language</label>
                    <select class="form-control" name="patient[language]" required>
                      <option value="ENG">English</option>
                      <option value="ESP">Spanish</option>
                    </select>
                </div>
            </div>
            <div class="form-row mt-1">
                <div class="col">
                    <label class="col-form-label">Address</label>
                    <input type="text" class="form-control" name="patient[address]" value="<%= @patient.address %>" placeholder="Enter Address" required>
                </div>
            </div>
            <div class="form-row mt-2">
                <div class="col">
                    <label class="col-form-label">City</label>
                    <input type="text" class="form-control" name="patient[city]" value="<%= @patient.city %>" placeholder="City" required>
                </div>
                <div class="col">
                    <label class="col-form-label">State</label>
                    <input type="text" class="form-control" name="patient[state]" value="<%= @patient.state %>" placeholder="State" required>
                </div>
                <div class="col">
                    <label class="col-form-label">Zip Code</label>
                    <input type="text" class="form-control" name="patient[zip]" value="<%= @patient.zip %>" placeholder="Zip" required>
                </div>
            </div>
                    
        </div>
        <div class="card-footer text-right">
            <button type="submit" class="btn btn-lg btn-success">Submit</button>
            <button type="button" class="btn btn-lg btn-danger mr-2" onMouseDown="hideModal()">Close</button>
        </div>
    </div>
<% end %>

app/views/patients/_new.html.erb
<%= form_for :patient, :url => "/patients"  do |f| %>
    <div class="card">
        <h5 class="card-header bg-dark text-light">Add New Patient Record</h5>
        <div class="card-body">
            <div class="form-row">
                <div class="col">
                    <label class="col-form-label">First Name</label>
                    <input type="text" class="form-control" name="patient[first_name]" placeholder="First name" required>
                </div>
                <div class="col">
                    <label class="col-form-label">Last Name</label>
                    <input type="text" class="form-control" name="patient[last_name]" placeholder="Last name" required>
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <label class="col-form-label">Gender</label>
                    <select class="form-control" name="patient[gender]" required>
                      <option value="M" >Male</option>
                      <option value="F" >Female</option>
                      <option value="O" >Other</option>
                    </select>
                </div>
                <div class="col">
                    <label class="col-form-label">Birthdate</label>
                    <input type="date" class="form-control" name="patient[birthdate]" placeholder="Date of Birth" required>
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <label class="col-form-label">MRN</label>
                    <input type="text" class="form-control" name="patient[epic_id]" placeholder="Enter Chart Number" required>
                </div>
                <div class="col">
                    <label class="col-form-label">Preferred Language</label>
                    <select class="form-control" name="patient[language]" required>
                      <option value="ENG">English</option>
                      <option value="ESP">Spanish</option>
                    </select>
                </div>
            </div>
            <div class="form-row mt-1">
                <div class="col">
                    <label class="col-form-label">Address</label>
                    <input type="text" class="form-control" name="patient[address]" placeholder="Enter Address" required>
                </div>
            </div>
            <div class="form-row mt-2">
                <div class="col">
                    <label class="col-form-label">City</label>
                    <input type="text" class="form-control" name="patient[city]" placeholder="City" required>
                </div>
                <div class="col">
                    <label class="col-form-label">State</label>
                    <input type="text" class="form-control" name="patient[state]" placeholder="State" required>
                </div>
                <div class="col">
                    <label class="col-form-label">Zip Code</label>
                    <input type="text" class="form-control" name="patient[zip]" placeholder="Zip" required>
                </div>
            </div>
                    
        </div>
        <div class="card-footer text-right">
            <button type="submit" class="btn btn-lg btn-success">Submit</button>
            <button type="button" class="btn btn-lg btn-danger mr-2" onMouseDown="hideModal()">Close</button>
        </div>
    </div>
<% end %>

app/views/patients/edit.js.erb
document.getElementById("modalContent").innerHTML = "<%= j (render partial: 'edit') %>"
document.getElementById("appModal").style.display = "block"
document.getElementById("appModal").classList.add("show")

app/views/patients/index.html.erb
<link href=<%= asset_path("bootstrap4-toggle.min.css") %> rel="stylesheet">
<link rel="stylesheet" type="text/css" href=<%= asset_path("datatables.min.css") %> />
<script type="text/javascript" src=<%= asset_path("datatables.min.js") %>> </script>
<script src=<%= asset_path("bootstrap4-toggle.min.js") %>></script>

<!-- Modal -->
<div class="modal fade" id="appModal" tabindex="-1" aria-labelledby="appModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content" id="modalContent">
      test
    </div>
  </div>
</div> 

<div class="page-header" style="margin: 0px !important;padding: 0px !important;">
  <h3><%=t '.title', :default => "Patient Registry" %></h3>
</div>

<div class="row">
    <div class="col-10">
        <table id="patients" class="table table-striped table-bordered" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Gender</th>
                    <th>Date of Birth</th>
                    <th style="text-align: center;">State</th>
                    <th>City</th>
                    <th style="width: 12.5%;">Actions</th>
                </tr>
            </thead>

            <tbody>
                <% (@patients || []).each do |patient| %>
                    <tr>
                        <td><%= link_to patient["first_name"],"/patients/#{patient['id']}"  %></td>
                        <td><%= link_to patient["last_name"],"/patients/#{patient['id']}"  %></td>
                        <td><%= patient.full_gender %></td>
                        <td><%= patient.formatted_dob %></td>
                        <td style="text-align: center;"><%= patient.state %></td>
                        <td><%= patient.city%></td>
                        <td style="text-align: center;">
                            <%= link_to "View","/patients/#{patient['id']}"  %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
    <div class="col-2">
        <div class="card mb-3">
            <div class="card-header text-white bg-info text-center"><h5 class="card-title">Patient Summary</h5></div>
            <div class="card-body ">
                <a href="/patients" class="card text-center text-decoration-none m-2">
                    <div class="card-body ">
                        <h5 class="card-subtitle">Total Patients</h5>
                        <p class="card-text"><%= @patient_count %></p>
                    </div>
                </a>
                <a href="/patients?pmap_only=true" class="card text-center text-decoration-none mt-3 m-1">
                    <div class="card-body">
                        <h5 class="card-subtitle">PMAP Patients</h5>
                        <p class="card-text"><%= @pmap_patients %></p>
                    </div>
                </a>
            </div>
        </div>
        <%= link_to '<button class="btn btn-primary btn-lg btn-block">Add Patient</button>'.html_safe, new_patient_path, remote: true %>        
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#patients').DataTable({
            "pageLength": 12,
            "lengthChange": false        
            });
    } );

    function hideModal(){
        document.getElementById("appModal").style.display = "none"
        document.getElementById("appModal").classList.remove("show")

    }
</script>

app/views/patients/new.js.erb
document.getElementById("modalContent").innerHTML = "<%= j (render partial: 'new') %>"
document.getElementById("appModal").style.display = "block"
document.getElementById("appModal").classList.add("show")

app/views/patients/show.html.erb
<link href=<%= asset_path("bootstrap4-toggle.min.css") %> rel="stylesheet">
<script src=<%= asset_path("bootstrap4-toggle.min.js") %>></script>
<script type="text/javascript" src=<%= asset_path("bootstrap-typeahead.js") %>> </script>
  
<!-- Modal -->
<div class="modal fade" id="appModal" tabindex="-1" aria-labelledby="appModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content" id="modalContent">
      test
    </div>
  </div>
</div>

<div class="row ">
  <div class="col mb-7">
    <div class="card border-dark" style="width: 75rem">
      <div class="card-header text-white bg-primary">Patient Details</div>
      <div class="card-body">
        <h4 class="card-title"><%= @patient.name %></h5>
        <table class="table">        
            <tr>
              <th scope="row">Birthdate</th>
              <td><%= @patient.formatted_dob %></td>
              <th>Age</th>
              <td><%= @patient.age %></td>
            </tr>
            <tr>
              <th scope="row">Gender</th>
              <td><%= @patient.full_gender %></td>
              <th>Preferred Language</th>
              <td>
                <input type="checkbox" data-on="ENG" data-off="ESP" <%= @patient.language == "ENG" ? 'checked' : 'unchecked' %> data-toggle="toggle" data-offstyle="dark" data-onstyle="success">
              </td>
            </tr>
            <tr>
              <th scope="row">Street Address</th>
              <td><%= @patient.address %></td>
              <th>City</th>
              <td><%= @patient.city %></td>
            </tr>
            <tr>
              <th scope="row">State</th>
              <td><%= @patient.state %></td>
              <th>Zip Code</th>
              <td><%= @patient.zip %></td>
            </tr>
        </table>
      </div>
    </div>
    <div class="card border-dark mt-3" style="width: 75rem">
      <div class="card-header text-white bg-secondary">Dispensation History</div>
      <div class="card-body">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Item</th>
              <th scope="col">Amount Dispensed</th>
              <th scope="col">Date Dispensed</th>
            </tr>
          </thead>
          <tbody>
            <% (@history || []).each do |dispensation| %>
              <tr>
                <td><%= dispensation.drug_name %></td>
                <td><%= dispensation.quantity%></td>
                <td><%= dispensation.dispensation_date.strftime('%b %d, %Y') %> </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col mb-5">
    <div class="card">
      <div class="card-header text-white bg-info">PMAP Details</div>
      <div class="card-body mb-3" style="max-height: 30vh;overflow:auto;">
        <% (@pmap_meds || []).each do |manfucturer, values|%>
          <h6 class="card-title"><%= manfucturer%></h6>
          <table class="table">
            <% (values || []).each do |item| %>
              <tr>
                <td><%= item[0]%></td>
                <td><%= item[1]%></td>
                <td>
                  <%= link_to image_tag('add'), "/pmap_inventories/new?patient_id=#{@patient.id}&mfn_id=#{item[2]}&rx=#{item[3]}", remote: true %>       
                </td>
              </tr>
            <% end %>
          </table>
        <% end %>
      </div>
    </div>
    <%= link_to '<button class="btn btn-primary btn-lg btn-block m-2 mt-4">Add PMAP Item</button>'.html_safe, "/pmap_inventories/new?patient_id=#{@patient.id}", remote: true %>       
    <%= link_to '<button class="btn btn-info btn-lg btn-block m-2">Edit Patient</button>'.html_safe, edit_patient_path(@patient), remote: true %>  
    <%= link_to '<button class="btn btn-warning btn-lg btn-block m-2">Dispense (No Rx)</button>'.html_safe, "/refill?patient_id=#{@patient.id}", remote: true %>        
    <%= link_to '<button class="btn btn-danger btn-lg btn-block m-2">Cancel</button>'.html_safe, patients_path %>         
  </div>
</div>


<script type="text/javascript">
    
    function hideModal(){
        document.getElementById("appModal").style.display = "none"
        document.getElementById("appModal").classList.remove("show")

    }

    $(function() {
            $('input:checkbox').change(function(e) {
                $.ajax({
                    url: '/update_language/' + <%= @patient.id %>,
                    type: 'POST',
                    headers: { 'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content') },
                    data: {'language': ($(this).prop('checked') ? "ENG" : "ESP")},
                    success: function(data) {
                        console.log('success')
                    },
                    error: function() {
                        console.log('failure')
                    }
                });
            })
        })
</script>