config/routes.rb
Rails.application.routes.draw do


  root "home#index"

  # Routes for the home controller
  get 'home/contact'
  get 'home/index'
  get 'home/about'
  get 'home/faq'
  get 'home/custom_report'
  get 'home/activity_sheet'
  post '/report' => "home#custom_report"
  get '/dispose_item/:id' => "home#dispose_item"
  get '/pharmacy_sheet/:date' => "home#activity_sheet"
  get '/provider_suggestions' => "home#provider_suggestions"
  get '/drug_name_suggestions' => "home#drug_name_suggestions"

  # Routes for the sessions controller

  get 'sessions/new'
  get 'sessions/destroy'
  post 'sessions/create'
  get "/login" => "sessions#new"
  get "/logout" => "sessions#destroy"

  # Routes for the general inventory 
  get "general_inventories/print/:id" => "general_inventories#print"
  get "/void_general_inventory/:id" => "general_inventories#delete", as: 'void_general_inventory'
  post "/delete_general_inventory_item/:id" => "general_inventories#destroy"


  # Routes for the pmap inventory 
  get "/reorders" => "pmap_inventories#reorders"
  get "pmap_inventories/print/:id" => "pmap_inventories#print"
  get "/move_pmap_inventory/:id" => "pmap_inventories#move_inventory"
  post "/delete_pmap_inventory_item/:id" => "pmap_inventories#destroy"
  get "/void_pmap_inventory/:id" => "pmap_inventories#delete", as: 'void_pmap_inventory'


  # Routes for prescriptions
  get "void_prescription/:id" => "prescriptions#void_prescription", as: 'void_prescription'
  get "ajax_prescriptions" => "prescriptions#ajax_prescriptions"
  get "dashboard" => "prescriptions#dashboard"

  # Routes for dispensaions
  get "print_dispensation_label" => "dispensations#print_dispensation_label"
  get "/refill" => "dispensations#refill"
  post "/refill" => "dispensations#refill"

  # Routes for users
  get "/new_user_role" => "users#new_user_role"
  post "users/create_user_role", as: 'create_user_role'

  # Routes for patients
  post "/update_language/:id" => "patients#update_language"


  # Routes for manufacturers
  post "/toggle_pmap/:id" => "manufacturers#toggle_pmap"
  get "/void_manufacturer/:id" => "manufacturers#delete", as: 'void_manufacturer'


  # Routes for news
  get "/void_news_item/:id" => "news#delete", as: 'void_news'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :news
  resources :users
  resources :patients
  resources :prescriptions
  resources :dispensations
  resources :manufacturers
  resources :pmap_inventories
  resources :general_inventories
end

app/models/general_inventory.rb
class GeneralInventory < ApplicationRecord
    has_one :rxnconso, :foreign_key => :rxaui
    before_save :complete_record
    before_create :complete_record
    attribute :name, :string
    #validates_associated :rxnconso

    include Misc

    def drug_name
      return Rxnconso.find_by_RXAUI(self.rxaui).STR
    end
    
    def bottle_id
        return self.gn_identifier
    end

    def formatted_identifier
      return self.gn_identifier
    end

    def formatted_lot_number
      return self.lot_number
    end

    def complete_record
      self.current_quantity = self.received_quantity
      self.date_received = Date.today
      unless !self.gn_identifier.blank?
        last_id = GeneralInventory.order(gn_inventory_id: :desc).first.id rescue "0"
        next_number = (last_id.to_i+1).to_s.rjust(6,"0")
        check_digit = calculate_check_digit(next_number)
        self.gn_identifier = "G#{next_number}#{check_digit}"
      end
      if self.rxaui.blank? and !self.name.blank?
        self.rxaui = Rxnconso.where("STR = ? and TTY in ('PSN', 'SCD')", self.name).first.RXAUI
      end
    end

    def self.aboutToExpire_items
      return GeneralInventory.where("voided = ? AND current_quantity > ? AND expiration_date  BETWEEN ? AND ?",
        false,0,Date.today.strftime('%Y-%m-%d'),Date.today.advance(:months => 2).end_of_month.strftime('%Y-%m-%d'))
    end

    def self.underStocked
      
    end

    def self.expired_items
      return GeneralInventory.where("voided = ? AND current_quantity > ? AND expiration_date <= ? ", false,0, Date.current.strftime('%Y-%m-%d'))
    end

    def self.wellStocked
    end

end

app/controllers/general_inventories_controller.rb
class GeneralInventoriesController < ApplicationController
    
    def index
        @items = GeneralInventory.where("current_quantity > ? and voided = ? ", 0, false)
        @aboutToExpire = GeneralInventory.aboutToExpire_items.length
        #@underStocked = underStocked.length
        @expired = GeneralInventory.expired_items.length
        #@wellStocked = wellStocked.length
    end

    def new
        @mfns = Manufacturer.select(["mfn_id", "name"])
        respond_to do |format|
            format.js {render layout: false}
            format.html { render 'edit'} # I had to tell rails to use the index by default if it's a html request. 
        end
    end
    
    def create
        new_item = GeneralInventory.create(gn_params)
        if new_item.errors.blank?
            flash[:success] = {title: "Inventory Item Added", message: "#{params[:general_inventory][:name]} was successfully added to inventory."}
            print_and_redirect("/general_inventories/print/#{new_item.bottle_id}", "/general_inventories")
        else
            flash[:errors] = {title: "Failed to Create Record", message: new_item.errors}
            redirect_to "/general_inventories"
        end
    end

    def edit
        @item = GeneralInventory.find(params[:id])
        @mfns = Manufacturer.select(["mfn_id", "name"])
        respond_to do |format|
          format.js {render layout: false}
          format.html { render 'edit'} # I had to tell rails to use the index by default if it's a html request. 
        end
    end

    def update
        
        item = GeneralInventory.find(params[:id])
        if item.blank?
            flash[:errors] = {title: "Failed to Update Record", message: "Item could not be found"}
        else
            item.lot_number = params[:general_inventory][:lot_number].upcase
            item.expiration_date = params[:general_inventory][:expiration_date].to_date rescue nil
            item.received_quantity = params[:general_inventory][:received_quantity].to_i + (item.received_quantity - item.current_quantity)
            item.current_quantity = params[:general_inventory][:received_quantity].to_i
            item.mfn_id = params[:general_inventory][:manufacturer]
            item.save
            if item.errors.blank?
                flash[:success] = {title: "Successfully deleted record", message: "#{item.drug_name} #{item.lot_number} was successfully deleted."}
                news = News.where("refers_to = ? AND resolved = ?", item.bottle_id, false).update({
                    :resolved => true,
                    :resolution => "Item was voided",
                    :date_resolved => Date.today
                })
            else
                flash[:errors] = {title: "Failed to Update Record", message: "Item could not be found"}
            end
            #logger.info "#{current_user.username} voided general inventory item #{params[:general_inventory][:gn_id]}"
        end

        redirect_to "/general_inventories"
    end

    def delete
        @item = GeneralInventory.find(params[:id])
        respond_to do |format|
            format.js {render layout: false}
            format.html { render 'delete'} # I had to tell rails to use the index by default if it's a html request. 
        end
    end

    def destroy
        item = GeneralInventory.where(:gn_identifier => params[:id]).update(gn_params)
        if item.blank?
            flash[:errors] = {title: "Failed to Delete Record", message: "Item with bottle id #{params[:id]} could not be found"}
        else
            flash[:success] = {title: "Successfully deleted record", message: "#{item.first.drug_name} #{item.first.lot_number} was successfully deleted."}
            news = News.where("refers_to = ? AND resolved = ?", item.first.bottle_id, false).update({
                :resolved => true,
                :resolution => "Item was voided",
                :date_resolved => Date.today
            })
            #logger.info "#{current_user.username} voided general inventory item #{params[:general_inventory][:gn_id]}"
        end

        redirect_to "/general_inventories"
    end
    
    def print
        entry = GeneralInventory.where("gn_identifier = ?", params[:id]).first 
        print_string = entry.create_bottle_label(entry.drug_name,params[:id],entry.expiration_date,entry.lot_number,"General", nil)
        send_data(print_string,:type=>"application/label; charset=utf-8", :stream=> true, :filename=>"#{entry.lot_number}#{rand(10000)}.lbl", :disposition => "inline")
        
    end  

    private

    def gn_params
      params.require(:general_inventory).permit(:voided_by,:void_reason, :voided,:rxaui, :mfn_id,:name, :lot_number, :expiration_date, :date_received, :received_quantity, :gn_inventory_id)
    end
end

app/helpers/general_inventories_helper.rb
module GeneralInventoriesHelper
end

app/views/general_inventories/_delete.html.erb
<%= form_for :general_inventory,:url => "/delete_general_inventory_item/#{@item.gn_identifier}", :method => "POST" do |f| %>
  <div class="card">
        <h5 class="card-header bg-dark text-light">Delete Item from Inventory</h5>
        <div class="card-body">
            <blockquote class="blockquote">
              <p class="mb-0">Select reason for deleting item</p>
            </blockquote>
            <fieldset class="form-group row">  
              <div class="col-sm-10">
                  <div class="form-check">
                      <input class="form-check-input" type="radio" name="general_inventory[void_reason]" id="gridRadios1" value="Medication has expired" required>
                      <label class="form-check-label" for="gridRadios1">Medication has expired</label>
                  </div>
                  <div class="form-check">
                      <input class="form-check-input" type="radio" name="general_inventory[void_reason]" id="gridRadios2" value="Clerical error when entering">
                      <label class="form-check-label" for="gridRadios2">Clerical error made when adding item</label>
                  </div>
                  <div class="form-check disabled">
                      <input class="form-check-input" type="radio" name="general_inventory[void_reason]" id="gridRadios3" value="Other">
                      <label class="form-check-label" for="gridRadios3">Other</label>
                  </div>
              </div>
          </fieldset>
        </div>
        <div class="card-footer text-right">
            <button type="submit" class="btn btn-lg btn-success">Confirm Delete</button>
            <button type="button" class="btn btn-lg btn-danger mr-2" onMouseDown="hideModal()">Close</button>
        </div>
    </div>
    <%= f.hidden_field :voided_by, :value => current_user.id %>
    <%= f.hidden_field :voided, :value => true %>
<% end %>

app/views/general_inventories/_edit.html.erb
<%= form_for :general_inventory, :html => { :class => "form-horizontal general_inventory" }, :url => "/general_inventories/#{params[:id]}", method: 'PUT'  do |f| %>
    <div class="card">
        <h5 class="card-header bg-secondary text-light">Edit General Inventory Item</h5>
        <div class="card-body">
            <div class="form-group row">
                <label for="itemName" class="col-md-3 col-form-label">Item Name</label>
                <div class="col-md-9">
                    <input type="text" readonly class="form-control-plaintext" id="itemName" value="<%= @item.drug_name%>" placeholder="Enter Item Name">
                </div>
            </div>
            <div class="form-group row">
                <label for="itemIdentifier" class="col-md-3 col-form-label">Item ID</label>
                <div class="col-md-9">
                    <input type="text" readonly class="form-control-plaintext" id="itemIdentifier" value="<%= @item.formatted_identifier%>" placeholder="Enter Item Identifier">
                </div>
            </div>
            <div class="form-group row">
                <label for="itemManufacturer" class="col-md-10 col-form-label">Manufacturer</label>
                <div class="col-md-11">
                    <select class="form-control" id="itemManufacturer" name="general_inventory[mfn__id]" placeholder="Enter Item Manufacturer" required>
                        <% (@mfns || []).each do |mfn| %>
                            <option <%= (@item.mfn_id || '') == mfn.mfn_id ? 'Selected' : ''%> value="<%= mfn.mfn_id %>"><%= mfn.name %></option>
                        <% end %>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="itemLotNumber" class="col-md-10 col-form-label">Lot Number</label>
                <div class="col-md-11">
                    <input type="text" class="form-control" id="itemLotNumber" name="general_inventory[lot_number]" value="<%= @item.lot_number %>" placeholder="Enter Item Lot Number" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="itemExpiryDate" class="col-md-10 col-form-label">Expiry Date</label>
                <div class="col-md-11">
                    <input type="date" class="form-control" id="itemExpiryDate" name="general_inventory[expiration_date]" value="<%= @item.expiration_date %>" placeholder="Enter Item Expiry Date" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="itemReceivedQn" class="col-md-10 col-form-label">Received Quantity</label>
                <div class="col-md-11">
                    <input type="number" class="form-control" id="itemReceivedQn" name="general_inventory[received_quantity]" value="<%= @item.received_quantity %>" placeholder="Enter Received Quantity" required>
                </div>
            </div>
        </div>
        <div class="card-footer text-right">
            <button type="submit" class="btn btn-success">Submit</button>
            <button type="button" class="btn btn-danger" onMouseDown="hideModal()">Close</button>
        </div>
    </div>
<% end %>

app/views/general_inventories/_new.html.erb
<%= form_for :general_inventory, :html => { :class => "form-horizontal general_inventory" }, :url => "/general_inventories"  do |f| %>
    <div class="card">
        <h5 class="card-header bg-dark text-light">Add New General Inventory Item</h5>
        <div class="card-body">
            <div class="form-group row">
                <label for="itemName" class="col-md-10 col-form-label">Item Name</label>
                <div class="col-md-11">
                    <input type="text" class="form-control" id="itemName"  placeholder="Enter Item Name" autocomplete="off" name="general_inventory[name]" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="itemManufacturer" class="col-md-10 col-form-label">Manufacturer</label>
                <div class="col-md-11">
                    <select class="selectpicker form-control" id="itemManufacturer" placeholder="Select Item Manufacturer" name="general_inventory[mfn_id]" required>
                        <% (@mfns || []).each do |mfn| %>
                            <option value="<%= mfn.mfn_id %>"><%= mfn.name %></option>
                        <% end %>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="itemLotNumber" class="col-md-10 col-form-label">Lot Number</label>
                <div class="col-md-11">
                    <input type="text" class="form-control" id="itemLotNumber" placeholder="Enter Item Lot Number" name="general_inventory[lot_number]" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="itemExpiryDate" class="col-md-10 col-form-label">Expiry Date</label>
                <div class="col-md-11">
                    <input type="date" class="form-control" id="itemExpiryDate" placeholder="Enter Item Expiry Date" name="general_inventory[expiration_date]" min="<%= Date.today.strftime('%Y-%m-%d') %>" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="itemReceivedQn" class="col-md-10 col-form-label">Received Quantity</label>
                <div class="col-md-11">
                    <input type="number" class="form-control" id="itemReceivedQn" placeholder="Enter Received Quantity" name="general_inventory[received_quantity]" required>
                </div>
            </div>
        </div>
        <div class="card-footer text-right">
            <button type="submit" class="btn btn-lg btn-success">Submit</button>
            <button type="button" class="btn btn-lg btn-danger mr-2" onMouseDown="hideModal()">Close</button>
        </div>
    </div>
<% end %>

app/views/general_inventories/index.html.erb
<link rel="stylesheet" type="text/css" href=<%= asset_path("datatables.min.css") %> />
<script type="text/javascript" src=<%= asset_path("datatables.min.js") %>> </script>
<script type="text/javascript" src=<%= asset_path("bootstrap-typeahead.js") %>> </script>

<!-- Modal -->
<div class="modal fade" id="appModal" tabindex="-1" aria-labelledby="appModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content" id="modalContent">
      test
    </div>
  </div>
</div>
<div>
    <h3><%=t '.title', :default => "General Inventory" %></h3>
</div>
<div class="row">
    <div class="col-10">
        <table id="inventory" class="table table-striped table-bordered" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Item</th>
                    <th>Item ID</th>
                    <th>Lot Number</th>
                    <th>Current Quantity</th>
                    <th>Expiration Date</th>
                    <th style="width: 12.5%;">Actions</th>
                </tr>
            </thead>

            <tbody>
                <% (@items || []).each do |item| %>
                    <tr>
                        <td><%= item.drug_name rescue "" %></td>
                        <td><%= item.formatted_identifier %></td>
                        <td><%= item.formatted_lot_number %></td>
                        <td style="text-align: center;"><%= item.current_quantity %></td>
                        <td ><%= item.expiration_date.strftime("%b-%Y") %></td>
                        <td style="text-align: center;">
                            <%= link_to image_tag('edit'), edit_general_inventory_path(item), remote: true %>                            
                            <%= link_to image_tag('print'), "/general_inventories/print/#{item.gn_identifier}" %>
                            <%= link_to image_tag('delete'), void_general_inventory_path(item), remote: true %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
    <div class="col-2">
        <div class="card mb-3">
            <div class="card-header text-white bg-info"><h5 class="card-title">Stock Summary</h5></div>
            <div class="card-body ">
                <a href="#" class="card text-center  m-2 text-decoration-none">
                    <div class="card-body">
                        <h5 class="card-title">Items in Stock</h5>
                        <p class="card-text">0</p>
                    </div>
                </a>
                <a href="#" class="card text-center mt-3 m-1 text-decoration-none">
                    <div class="card-body">
                        <h5 class="card-title">Understocked Items</h5>
                        <p class="card-text">0</p>
                    </div>
                </a>
                <a href="#" class="card text-center mt-3 m-1 text-decoration-none">
                    <div class="card-body">
                        <h5 class="card-title">Items About to Expire</h5>
                        <p class="card-text"><%= @aboutToExpire %></p>
                    </div>
                </a>
                <a href="#" class="card text-center mt-3 m-1 text-decoration-none">
                    <div class="card-body">
                        <h5 class="card-title">Expired Items</h5>
                        <p class="card-text"><%= @expired %></p>
                    </div>
                </a>
            </div>
        </div>
        <%= link_to '<button class="btn btn-primary btn-lg btn-block">Add Item</button>'.html_safe, new_general_inventory_path, remote: true %>        
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#inventory').DataTable({
            "lengthChange": false
        });

        $('#itemName').typeahead({
          ajax: { 
                url: '/drug_name_suggestions',
                triggerLength: 2 
              }
        });
    } );


    function hideModal(){
        document.getElementById("appModal").style.display = "none"
        document.getElementById("appModal").classList.remove("show")

    }

</script>

app/views/general_inventories/new.js.erb
document.getElementById("modalContent").innerHTML = "<%= j (render partial: 'new') %>"
document.getElementById("appModal").style.display = "block"
document.getElementById("appModal").classList.add("show")