config/routes.rb
Rails.application.routes.draw do


  root "home#index"

  # Routes for the home controller
  get 'home/contact'
  get 'home/index'
  get 'home/about'
  get 'home/faq'
  get 'home/custom_report'
  get 'home/activity_sheet'
  post '/report' => "home#custom_report"
  get '/dispose_item/:id' => "home#dispose_item"
  get '/pharmacy_sheet/:date' => "home#activity_sheet"
  get '/provider_suggestions' => "home#provider_suggestions"
  get '/drug_name_suggestions' => "home#drug_name_suggestions"

  # Routes for the sessions controller

  get 'sessions/new'
  get 'sessions/destroy'
  post 'sessions/create'
  get "/login" => "sessions#new"
  get "/logout" => "sessions#destroy"

  # Routes for the general inventory 
  get "general_inventories/print/:id" => "general_inventories#print"
  get "/void_general_inventory/:id" => "general_inventories#delete", as: 'void_general_inventory'
  post "/delete_general_inventory_item/:id" => "general_inventories#destroy"


  # Routes for the pmap inventory 
  get "/reorders" => "pmap_inventories#reorders"
  get "pmap_inventories/print/:id" => "pmap_inventories#print"
  get "/move_pmap_inventory/:id" => "pmap_inventories#move_inventory"
  post "/delete_pmap_inventory_item/:id" => "pmap_inventories#destroy"
  get "/void_pmap_inventory/:id" => "pmap_inventories#delete", as: 'void_pmap_inventory'


  # Routes for prescriptions
  get "void_prescription/:id" => "prescriptions#void_prescription", as: 'void_prescription'
  get "ajax_prescriptions" => "prescriptions#ajax_prescriptions"
  get "dashboard" => "prescriptions#dashboard"

  # Routes for dispensaions
  get "print_dispensation_label" => "dispensations#print_dispensation_label"
  get "/refill" => "dispensations#refill"
  post "/refill" => "dispensations#refill"

  # Routes for users
  get "/new_user_role" => "users#new_user_role"
  post "users/create_user_role", as: 'create_user_role'

  # Routes for patients
  post "/update_language/:id" => "patients#update_language"


  # Routes for manufacturers
  post "/toggle_pmap/:id" => "manufacturers#toggle_pmap"
  get "/void_manufacturer/:id" => "manufacturers#delete", as: 'void_manufacturer'


  # Routes for news
  get "/void_news_item/:id" => "news#delete", as: 'void_news'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :news
  resources :users
  resources :patients
  resources :prescriptions
  resources :dispensations
  resources :manufacturers
  resources :pmap_inventories
  resources :general_inventories
end

app/models/pmap_inventory.rb
class PmapInventory < ApplicationRecord
    has_one :rxnconso, :foreign_key => :rxaui
    #has_one :manufacturer, :foreign_key => :manufacturer
    belongs_to :patient, :foreign_key => :patient_id
    before_save :complete_record

    attribute :name, :string
    attribute :mfn_id, :string

    include Misc

    def drug_name
      return Rxnconso.find_by_RXAUI(self.rxaui).STR
    end
    
    def bottle_id
        return self.pap_identifier
    end

    def formatted_identifier
      return self.pap_identifier
    end

    def formatted_lot_number
      return self.lot_number
    end

    def manufactured_by
      return Manufacturer.find(self.manufacturer).name 
    end

    def owner
      return self.patient.name
    end

    def complete_record
      self.current_quantity = self.received_quantity
      self.date_received = Date.today
      unless !self.pap_identifier.blank?
        last_id = PmapInventory.order(pap_inventory_id: :desc).first.id rescue "0"
        next_number = (last_id.to_i+1).to_s.rjust(6,"0")
        check_digit = calculate_check_digit(next_number)
        self.pap_identifier = "P#{next_number}#{check_digit}"
      end
      if self.rxaui.blank? and !self.name.blank?
        self.rxaui = Rxnconso.where("STR = ? and TTY in ('PSN', 'SCD')", self.name).first.RXAUI
      end
      if self.manufacturer.blank? and !self.mfn_id.blank?
        self.manufacturer = self.mfn_id
      end
    end

    def self.aboutToExpire_items
      return PmapInventory.where("voided = ? AND current_quantity > ? AND expiration_date  BETWEEN ? AND ?",
        false,0,Date.today.strftime('%Y-%m-%d'),Date.today.advance(:months => 2).end_of_month.strftime('%Y-%m-%d'))
    end

    def self.underStocked
      
    end

    def self.expired_items
      return PmapInventory.where("voided = ? AND current_quantity > ? AND expiration_date <= ? ", false,0, Date.current.strftime('%Y-%m-%d'))
    end

    def self.wellStocked
      return PmapInventory.select("patient_id, rxaui, count(rxaui) as count").where("current_quantity > 0 and voided = ?",false).group(:patient_id,:rxaui)
    end

    def self.move_to_general(bottle_id)
      item = PmapInventory.find_by_pap_identifier_and_voided(bottle_id,false)
  
      unless item.blank?
        PmapInventory.transaction do
          item.voided = true
          item.void_reason = "Moved to general inventory"
          item.manufacturer = "Unknown" if item.manufacturer.blank?
  
          if item.save
            new_stock_entry = GeneralInventory.new
            new_stock_entry.lot_number = item.lot_number.upcase
            new_stock_entry.expiration_date = item.expiration_date rescue nil
            new_stock_entry.received_quantity = item.current_quantity
            new_stock_entry.current_quantity = item.current_quantity
            new_stock_entry.rxaui = item.rxaui
            new_stock_entry.gn_identifier= item.pap_identifier
            new_stock_entry.save
            return new_stock_entry
          end
        end
      end
      return false
    end
end

app/controllers/pmap_inventories_controller.rb
class PmapInventoriesController < ApplicationController
    def index
        @items = PmapInventory.where("current_quantity > ? and voided = ? ", 0, false)
        @aboutToExpire = PmapInventory.aboutToExpire_items.length
        @underStocked = News.where({:resolved => false, :news_type => "under utilized item"}).length
        @expired = PmapInventory.expired_items.length
        @wellStocked = PmapInventory.wellStocked.length
    end

    def show
        @item = PmapInventory.find(params[:id]) rescue nil

        if @item.blank?
          redirect_to "/reorders"
        else
          @inventory = PmapInventory.where("voided = ? AND current_quantity > 0 AND patient_id = ? AND rxaui = ?",
                                           false, @item.patient_id, @item.rxaui).order(date_received: :asc)
          @prescriptions = Prescription.where("voided = ? AND patient_id = ? AND rxaui = ?", false, @item.patient_id,
                                              @item.rxaui).order(date_prescribed: :asc)
          @patient = @item.patient
        end
    end

    def create
        
        new_item = PmapInventory.create(pmap_params)
        
        if new_item.errors.blank?
            flash[:success] = {title: "Inventory Item Added", message: "#{params[:pmap_inventory][:name]} was successfully added to inventory."}
            print_and_redirect("/pmap_inventories/print/#{new_item.bottle_id}", "/patients/#{params[:pmap_inventory][:patient_id]}")
        else
            flash[:errors] = {title: "Failed to Create Record", message: new_item.errors}
            redirect_to "/patients/#{params[:pmap_inventory][:patient_id]}"
        end
    end

    def new
        @patient = Patient.find(params[:patient_id])
        if !params[:mfn_id].blank?
            @mfn = Manufacturer.find(params[:mfn_id]).name
            @drug = Rxnconso.find_by_RXAUI(params[:rx]).STR
        end
        @mfns = Manufacturer.select("mfn_id,name").where(:has_pmap => true, :voided => false)
        respond_to do |format|
            format.js {render layout: false}
            format.html { render 'new'} # I had to tell rails to use the index by default if it's a html request. 
        end
    end

    def print
        entry = PmapInventory.where("pap_identifier = ?", params[:id]).first 
        print_string = entry.create_bottle_label(entry.drug_name,params[:id],entry.expiration_date,entry.lot_number,"PMAP", entry.owner)
        send_data(print_string,:type=>"application/label; charset=utf-8", :stream=> true, :filename=>"#{entry.lot_number}#{rand(10000)}.lbl", :disposition => "inline")
    end
    
    def edit
        @item = PmapInventory.find(params[:id])
        @mfns = Manufacturer.select(["mfn_id", "name"]).where(:has_pmap => true, :voided => false)
        respond_to do |format|
            format.js {render layout: false}
            format.html { render 'edit'} # I had to tell rails to use the index by default if it's a html request. 
        end
    end

    def update
        item = PmapInventory.find(params[:id])
        if item.blank?
            flash[:errors] = {title: "Failed to Update Record", message: "Item could not be found"}
        else
            item.lot_number = params[:pmap_inventory][:lot_number].upcase
            item.reorder_date = params[:pmap_inventory][:reorder_date].to_date rescue nil
            item.expiration_date = params[:pmap_inventory][:expiration_date].to_date rescue nil
            item.received_quantity = params[:pmap_inventory][:received_quantity].to_i + (item.received_quantity - item.current_quantity)
            item.current_quantity = params[:pmap_inventory][:received_quantity].to_i
            item.mfn_id = params[:pmap_inventory][:mfn_id]
            item.save
            if item.errors.blank?
                flash[:success] = {title: "Successfully deleted record", message: "#{item.drug_name} #{item.lot_number} was successfully deleted."}
                news = News.where("refers_to = ? AND resolved = ?", item.bottle_id, false).update({
                    :resolved => true,
                    :resolution => "Item was voided",
                    :date_resolved => Date.today
                })
            else
                flash[:errors] = {title: "Failed to Update Record", message: "Item could not be found"}
            end
            #logger.info "#{current_user.username} voided pmap inventory item #{params[:id]}"
        end
        
        redirect_to "/pmap_inventories"
    end

    def delete
        @item = PmapInventory.find(params[:id])
        respond_to do |format|
            format.js {render layout: false}
            format.html { render 'delete'} # I had to tell rails to use the index by default if it's a html request. 
        end
    end

    def destroy
        item = PmapInventory.where(:pap_identifier => params[:id]).update(pmap_params)
        if item.blank?
            flash[:errors] = {title: "Failed to Delete Record", message: "Item with bottle id #{params[:id]} could not be found"}
        else
            flash[:success] = {title: "Successfully deleted record", message: "#{item.first.drug_name} #{item.first.lot_number} was successfully deleted."}
            news = News.where("refers_to = ? AND resolved = ?", item.first.bottle_id, false).update({
                :resolved => true,
                :resolution => "Item was voided",
                :date_resolved => Date.today
            })
            #logger.info "#{current_user.username} voided general inventory item #{params[:general_inventory][:gn_id]}"
        end

        redirect_to "/pmap_inventories"
    end
    
    def reorders
        reorders = PmapInventory.where("reorder_date between ? AND ? AND voided = ?",
                                       Date.today.beginning_of_week.strftime("%Y-%m-%d"),
                                       Date.today.end_of_week.strftime("%Y-%m-%d"),false )
    
        @reorders = view_context.reorders(reorders)
    end

    def move_inventory
        #Move pmap item to general inventory
    
        result = PmapInventory.move_to_general(params[:id])
    
        if result.blank?
          flash[:errors] = {} if flash[:errors].blank?
          flash[:errors][:missing] = ["Item with bottle ID #{params[:id]} was not found"]
        elsif result.errors.blank?
          News.resolve(params[:id],"under utilized item","Moved to general inventory")
          flash[:success] = {title: "Transfer Successful", message: "#{result.drug_name} #{result.lot_number} was successfully moved to general inventory."}
        else
          flash[:errors] = {title: "Transfer Unsuccessful", message: "Item with bottle id #{params[:id]} could not be transferred"}
        end
        
        redirect_to "/pmap_inventories"
      end

    private 
    def pmap_params
        params.require(:pmap_inventory).permit(:voided_by,:void_reason, :voided,:rxaui,:patient_id, :manufacturer, :mfn_id,:name, :lot_number, :reorder_date, :expiration_date, :date_received, :received_quantity, :pap_inventory_id)
    end
end

app/helpers/pmap_inventories_helper.rb
module PmapInventoriesHelper
    def reorders(inventory)
        results = []
        (inventory || []).each do |item|
          results << {"patient_name" => item.owner,
                      "patient_gender" => item.patient.full_gender,
                      "patient_birthdate" => item.patient.formatted_dob,
                      "drug" => item.drug_name,
                      "reorder_date" => item.reorder_date.to_date.strftime('%b %d, %Y'),
                      "manufacturer" => item.manufactured_by,
                      "id" => item.id}
        end
        return results
    end
end

app/views/pmap_inventories/_delete.html.erb
<%= form_for :pmap_inventory,:url => "/delete_pmap_inventory_item/#{@item.pap_identifier}", :method => "POST" do |f| %>
  <div class="card">
        <h5 class="card-header bg-dark text-light">Delete Item from Inventory</h5>
        <div class="card-body">
            <blockquote class="blockquote">
              <p class="mb-0">Select reason for deleting item</p>
            </blockquote>
            <fieldset class="form-group row">  
              <div class="col-sm-10">
                  <div class="form-check">
                      <input class="form-check-input" type="radio" name="pmap_inventory[void_reason]" id="gridRadios1" value="Medication has expired" required>
                      <label class="form-check-label" for="gridRadios1">Medication has expired</label>
                  </div>
                  <div class="form-check">
                      <input class="form-check-input" type="radio" name="pmap_inventory[void_reason]" id="gridRadios2" value="Clerical error when entering">
                      <label class="form-check-label" for="gridRadios2">Clerical error made when adding item</label>
                  </div>
                  <div class="form-check disabled">
                      <input class="form-check-input" type="radio" name="pmap_inventory[void_reason]" id="gridRadios3" value="Other">
                      <label class="form-check-label" for="gridRadios3">Other</label>
                  </div>
              </div>
          </fieldset>
        </div>
        <div class="card-footer text-right">
            <button type="submit" class="btn btn-lg btn-success">Confirm Delete</button>
            <button type="button" class="btn btn-lg btn-danger mr-2" onMouseDown="hideModal()">Close</button>
        </div>
    </div>
    <%#= f.hidden_field :voided_by, :value => current_user.id %>
    <%= f.hidden_field :voided, :value => true %>
<% end %>

app/views/pmap_inventories/_edit.html.erb
<%= form_for :pmap_inventory, :url => "/pmap_inventories/#{params[:id]}", method: 'PUT'  do |f| %>
    <div class="card">
        <h5 class="card-header bg-secondary text-light">Edit PMAP Inventory Item</h5>
        <div class="card-body">
            <div class="form-group row">
                <label for="itemName" class="col-md-3 col-form-label">Item Name</label>
                <div class="col-md-9">
                    <input type="text" readonly class="form-control-plaintext" id="itemName" value="<%= @item.drug_name%>" placeholder="Enter Item Name">
                </div>
            </div>
            <div class="form-group row">
                <label for="itemIdentifier" class="col-md-3 col-form-label">Item ID</label>
                <div class="col-md-9">
                    <input type="text" readonly class="form-control-plaintext" id="itemIdentifier" value="<%= @item.formatted_identifier%>" placeholder="Enter Item Identifier">
                </div>
            </div>
            <div class="form-group row">
                <label for="itemManufacturer" class="col-md-10 col-form-label">Manufacturer</label>
                <div class="col-md-11">
                    <select class="form-control" id="itemManufacturer" name="pmap_inventory[mfn_id]" placeholder="Enter Item Manufacturer" required>
                        <% (@mfns || []).each do |mfn| %>
                            <option <%= (@item.mfn_id || '') == mfn.mfn_id ? 'Selected' : ''%> value="<%= mfn.id %>"><%= mfn.name %></option>
                        <% end %>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="itemLotNumber" class="col-md-10 col-form-label">Lot Number</label>
                <div class="col-md-11">
                    <input type="text" class="form-control" id="itemLotNumber" name="pmap_inventory[lot_number]" value="<%= @item.lot_number %>" placeholder="Enter Item Lot Number" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="itemExpiryDate" class="col-md-10 col-form-label">Expiry Date</label>
                <div class="col-md-11">
                    <input type="date" class="form-control" id="itemExpiryDate" name="pmap_inventory[expiration_date]" value="<%= @item.expiration_date %>" placeholder="Enter Item Expiry Date" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="itemReorderDate" class="col-md-10 col-form-label">Reorder Date</label>
                <div class="col-md-11">
                    <input type="date" class="form-control" id="itemReorderDate" name="pmap_inventory[order_date]" value="<%= @item.reorder_date %>" placeholder="Enter Item Reorder Date" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="itemReceivedQn" class="col-md-10 col-form-label">Received Quantity</label>
                <div class="col-md-11">
                    <input type="number" class="form-control" id="itemReceivedQn" name="pmap_inventory[received_quantity]" value="<%= @item.received_quantity %>" placeholder="Enter Received Quantity" required>
                </div>
            </div>
        </div>
        <div class="card-footer text-right">
            <button type="submit" class="btn btn-success">Submit</button>
            <button type="button" class="btn btn-danger" onMouseDown="hideModal()">Close</button>
        </div>
    </div>
<% end %>

app/views/pmap_inventories/_new.html.erb
<%= form_for :pmap_inventory, :url => "/pmap_inventories"  do |f| %>
    <div class="card">
        <h5 class="card-header bg-dark text-light">Add New PMAP Inventory Item</h5>
        <div class="card-body">
            <div class="form-group row">
                <label for="itemName" class="col-md-10 col-form-label">Item Name</label>
                <div class="col-md-11">
                    <input type="text" class="form-control" id="itemName"  placeholder="Enter Item Name" autocomplete="off" name="pmap_inventory[name]" value="<%= (@drug || '')%>" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="itemManufacturer" class="col-md-10 col-form-label">Manufacturer</label>
                <div class="col-md-11">
                    <select class="selectpicker form-control" id="itemManufacturer" placeholder="Select Item Manufacturer" name="pmap_inventory[mfn_id]" required>
                        <% (@mfns || []).each do |mfn| %>
                            <option value="<%= mfn.mfn_id %>" <%= (@mfn || '') == mfn.name ? 'Selected' : ''%>><%= mfn.name %></option>
                        <% end %>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label for="itemLotNumber" class="col-md-10 col-form-label">Lot Number</label>
                <div class="col-md-11">
                    <input type="text" class="form-control" id="itemLotNumber" placeholder="Enter Item Lot Number" name="pmap_inventory[lot_number]" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="itemExpiryDate" class="col-md-10 col-form-label">Expiry Date</label>
                <div class="col-md-11">
                    <input type="date" class="form-control" id="itemExpiryDate" placeholder="Enter Item Expiry Date" name="pmap_inventory[expiration_date]" min="<%= Date.today.strftime('%Y-%m-%d') %>" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="itemReorderDate" class="col-md-10 col-form-label">Reorder Date</label>
                <div class="col-md-11">
                    <input type="date" class="form-control" id="itemReorderDate" placeholder="Reorder date (Month Day Year)" name="pmap_inventory[reorder_date]" min="<%= Date.today.strftime('%Y-%m-%d') %>" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="itemReceivedQn" class="col-md-10 col-form-label">Received Quantity</label>
                <div class="col-md-11">
                    <input type="number" class="form-control" id="itemReceivedQn" placeholder="Enter Received Quantity" name="pmap_inventory[received_quantity]" required>
                </div>
            </div>
        </div>
        <div class="card-footer text-right">
            <button type="submit" class="btn btn-lg btn-success">Submit</button>
            <button type="button" class="btn btn-lg btn-danger mr-2" onMouseDown="hideModal()">Close</button>
        </div>
    </div>
    <%= f.hidden_field :patient_id, :value => @patient.id %>
<% end %>

app/views/pmap_inventories/create.html.erb
<html>
<style>
    body{
        font-family: "Nimbus Sans L", "Arial Narrow", sans-serif;
    }


    <% if @show_next_button %>
    .page_button {
        display:block;
        font-size: 0.8em;
        color: black;
        background-color: lightgray;
        margin: 15px;
        border: 3px outset gray;
        -moz-user-select:none;
        width: 100px;
        height: 70px;
        text-align: center;
    }

    #filing_info {
        font-size:25px;
        -moz-user-select:none;
    }
    #patients_info_div{
        left:28px;
        position:absolute;
        top:0px;
        font-size:17;
        -moz-user-select:none;
    }
    td , th {
        text-align:center;
        border: 20px solid white;
        padding: 10px;
    }

    .filing_instraction {
        text-align:left;
    }

    .old_label {
        background-color:#FFFF99;
    }

    .new_label {
        background-color:lightgreen;
    }

    .active_heading {
        background-color:black;
        color:white;
    }

    #footer {
        background-color: #333333;
        bottom: 0;
        color: #CADCEA;
        height: 80px;
        overflow: hidden;
        padding-right: 20px;
        position: absolute;
        width: 98%;
    }

    <%end%>
</style>

<script>


    function done() {
        document.location = "<%=@redirect_url%>"
    }
</script>



<% if not @show_next_button %>
    <body>
    <br/><br/><br/>
    <center><h1><%=h @message %></h1></center>
    <iframe src="<%= @print_url %>" style='display:none'></iframe>
    </body>
    <script>
        setTimeout(redirect, 3000);
        function redirect(){
            document.location = '<%= @redirect_url %>'
        }
    </script>
<%else%>
    <body onload="setAttributes();">
    <%=@message%>
    <iframe src="/" style='display:none'></iframe>
    </body>
<%end%>
</html>

app/views/pmap_inventories/edit.js.erb
document.getElementById("modalContent").innerHTML = "<%= j (render partial: 'edit') %>"
document.getElementById("appModal").style.display = "block"
document.getElementById("appModal").classList.add("show")

app/views/pmap_inventories/index.html.erb
<link rel="stylesheet" type="text/css" href=<%= asset_path("datatables.min.css") %> />
<script type="text/javascript" src=<%= asset_path("datatables.min.js") %>> </script>
<script type="text/javascript" src=<%= asset_path("bootstrap-typeahead.js") %>> </script>

<!-- Modal -->
<div class="modal fade" id="appModal" tabindex="-1" aria-labelledby="appModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content" id="modalContent">
      test
    </div>
  </div>
</div>
<div>
    <h3><%=t '.title', :default => "PMAP Inventory" %></h3>
</div>
<div class="row">
    <div class="col-10">
        <table id="inventory" class="table table-striped table-bordered" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Item</th>
                    <th>Item ID</th>
                    <th>Patient</th>
                    <th>Lot Number</th>
                    <th>Current Quantity</th>
                    <th>Expiration Date</th>
                    <th style="width: 12.5%;">Actions</th>
                </tr>
            </thead>

            <tbody>
                <% (@items || []).each do |item| %>
                    <tr>
                        <td><%= item.drug_name rescue "" %></td>
                        <td><%= item.formatted_identifier %></td>
                        <td><%= link_to item.owner, "/patients/#{item.patient_id}" %></td>
                        <td><%= item.formatted_lot_number %></td>
                        <td style="text-align: center;"><%= item.current_quantity %></td>
                        <td ><%= item.expiration_date.strftime("%b-%Y") %></td>
                        <td style="text-align: center;">
                            <%= link_to image_tag('edit'), edit_pmap_inventory_path(item), remote: true %>                            
                            <%= link_to image_tag('print'), "/pmap_inventories/print/#{item.pap_identifier}" %>
                            <%= link_to image_tag('delete'), void_pmap_inventory_path(item), remote: true %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
    <div class="col-2">
        <div class="card mb-3">
            <div class="card-header text-white bg-info"><h5 class="card-title">Stock Summary</h5></div>
            <div class="card-body ">
                <a href="#" class="card text-center  m-2 text-decoration-none">
                    <div class="card-body">
                        <h5 class="card-title">Items in Stock</h5>
                        <p class="card-text">0</p>
                    </div>
                </a>
                <a href="#" class="card text-center mt-3 m-1 text-decoration-none">
                    <div class="card-body">
                        <h5 class="card-title">Understocked Items</h5>
                        <p class="card-text">0</p>
                    </div>
                </a>
                <a href="#" class="card text-center mt-3 m-1 text-decoration-none">
                    <div class="card-body">
                        <h5 class="card-title">Items About to Expire</h5>
                        <p class="card-text"><%= @aboutToExpire %></p>
                    </div>
                </a>
                <a href="#" class="card text-center mt-3 m-1 text-decoration-none">
                    <div class="card-body">
                        <h5 class="card-title">Expired Items</h5>
                        <p class="card-text"><%= @expired %></p>
                    </div>
                </a>
            </div>
        </div>
        <%#= link_to '<button class="btn btn-primary btn-lg btn-block">Add Item</button>'.html_safe, new_pmap_inventory_path, remote: true %>        
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#inventory').DataTable({
            "lengthChange": false
        });

        $('#itemName').typeahead({
          ajax: { 
                url: '/drug_name_suggestions',
                triggerLength: 2 
              }
        });
    } );


    function hideModal(){
        document.getElementById("appModal").style.display = "none"
        document.getElementById("appModal").classList.remove("show")

    }

</script>

app/views/pmap_inventories/new.js.erb
document.getElementById("modalContent").innerHTML = "<%= j (render partial: 'new') %>"
document.getElementById("appModal").style.display = "block"
document.getElementById("appModal").classList.add("show")


$(function() {
    
    $('#itemName').typeahead({
        ajax: { 
            url: '/drug_name_suggestions',
            triggerLength: 2 
            }
    });
});

app/views/pmap_inventories/reorders.html.erb
<link rel="stylesheet" type="text/css" href=<%= asset_path("datatables.min.css") %> />
<script type="text/javascript" src=<%= asset_path("datatables.min.js") %>> </script>

<div class="page-header" style="margin: 0px !important;padding: 0px !important;">
  <h3><%=t '.title', :default => "PMAP Reorders" %></h3>
</div>

<div class="row">
    <div class="col-12">
        <table id="reorders" class="table table-striped table-bordered" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Patient Name</th>
                    <th>Gender</th>
                    <th>Date of Birth</th>
                    <th style="text-align: center;">Drug Name</th>
                    <th>Reorder Date</th>
                    <th>Company</th>
                    <th style="width: 12.5%;">Actions</th>
                </tr>
            </thead>

            <tbody>
                <% i = 1 %>
                <% (@reorders || []).each do |item| %>
                    <tr>
                        <td><%= item["patient_name"] %></td>
                        <td><%= item["patient_gender"] %></td>
                        <td><%= item["patient_birthdate"] %></td>
                        <td><%= item["drug"] %></td>
                        <td><%= item["reorder_date"]%></td>
                        <td><%= item["manufacturer"]%></td>
                        <td style="text-align: center;">
                        <%= link_to "View","/pmap_inventories/#{item['id']}"  %>
                        </td>
                    </tr>
                    <% i += 1 %>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#reorders').DataTable({
            "pageLength": 9,
            "lengthChange": false        
            });
    } );
</script>