config/routes.rb
Rails.application.routes.draw do


  root "home#index"

  # Routes for the home controller
  get 'home/contact'
  get 'home/index'
  get 'home/about'
  get 'home/faq'
  get 'home/custom_report'
  get 'home/activity_sheet'
  post '/report' => "home#custom_report"
  get '/dispose_item/:id' => "home#dispose_item"
  get '/pharmacy_sheet/:date' => "home#activity_sheet"
  get '/provider_suggestions' => "home#provider_suggestions"
  get '/drug_name_suggestions' => "home#drug_name_suggestions"

  # Routes for the sessions controller

  get 'sessions/new'
  get 'sessions/destroy'
  post 'sessions/create'
  get "/login" => "sessions#new"
  get "/logout" => "sessions#destroy"

  # Routes for the general inventory 
  get "general_inventories/print/:id" => "general_inventories#print"
  get "/void_general_inventory/:id" => "general_inventories#delete", as: 'void_general_inventory'
  post "/delete_general_inventory_item/:id" => "general_inventories#destroy"


  # Routes for the pmap inventory 
  get "/reorders" => "pmap_inventories#reorders"
  get "pmap_inventories/print/:id" => "pmap_inventories#print"
  get "/move_pmap_inventory/:id" => "pmap_inventories#move_inventory"
  post "/delete_pmap_inventory_item/:id" => "pmap_inventories#destroy"
  get "/void_pmap_inventory/:id" => "pmap_inventories#delete", as: 'void_pmap_inventory'


  # Routes for prescriptions
  get "void_prescription/:id" => "prescriptions#void_prescription", as: 'void_prescription'
  get "ajax_prescriptions" => "prescriptions#ajax_prescriptions"
  get "dashboard" => "prescriptions#dashboard"

  # Routes for dispensaions
  get "print_dispensation_label" => "dispensations#print_dispensation_label"
  get "/refill" => "dispensations#refill"
  post "/refill" => "dispensations#refill"

  # Routes for users
  get "/new_user_role" => "users#new_user_role"
  post "users/create_user_role", as: 'create_user_role'

  # Routes for patients
  post "/update_language/:id" => "patients#update_language"


  # Routes for manufacturers
  post "/toggle_pmap/:id" => "manufacturers#toggle_pmap"
  get "/void_manufacturer/:id" => "manufacturers#delete", as: 'void_manufacturer'


  # Routes for news
  get "/void_news_item/:id" => "news#delete", as: 'void_news'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :news
  resources :users
  resources :patients
  resources :prescriptions
  resources :dispensations
  resources :manufacturers
  resources :pmap_inventories
  resources :general_inventories
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
    self.primary_key = 'mfn_id'
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
    def index
        if !params[:has_pmap].blank? 
            @manufacturers = Manufacturer.where(:has_pmap => true, :voided => false)
        elsif !params[:supports_us].blank?
            @manufacturers = Manufacturer.where("mfn_id in (?)", PmapInventory.where(:voided => false ).pluck(:manufacturer).uniq)
        else
            @manufacturers = Manufacturer.where(:voided => false)
        end
        
    end

    def create
        new_manufacturer = Manufacturer.create(mfn_params)

        if new_manufacturer.errors.blank?
            flash[:success] = {message: "#{new_manufacturer.name.titleize} was successfully added.", title:"Manufacturer Created"}
        else
            flash[:errors] = {message: "Manufacturer Could Not Be Added.", title:"Manufacturer Not Created"}
        end

        redirect_to "/manufacturers"
    end

    def new
        respond_to do |format|
            format.js {render layout: false}
            format.html { render 'new'} # I had to tell rails to use the index by default if it's a html request. 
        end
    end

    def edit
        @manufacturer = Manufacturer.find(params[:id])
        respond_to do |format|
            format.js {render layout: false}
            format.html { render 'edit'} # I had to tell rails to use the index by default if it's a html request. 
        end
    end

    def update
        mfn = Manufacturer.where("mfn_id = ? ", params[:manufacturer][:mfn_id]).update(mfn_params)
        if mfn.first.errors.blank? 
            flash[:success] = {message: "Successfully voided manufacturer #{mfn.first.name}", title: "Manufacturer Updated"}
        else
            flash[:errors] = {message: "Could not delete manufacturer", title: "Manufacturer Not Updated"}
        end
        
        redirect_to "/manufacturers"
    end

    def delete
        @manufacturer = Manufacturer.find(params[:id])
        respond_to do |format|
            format.js {render layout: false}
            format.html { render 'delete'} # I had to tell rails to use the index by default if it's a html request. 
        end
    end

    def destroy
        mfn = Manufacturer.where("mfn_id = ? ", params[:id]).update(:voided => true)
        if mfn.first.errors.blank? 
            flash[:success] = {message: "Successfully voided manufacturer #{mfn.first.name}", title: "Manufacturer Deleted"}
        else
            flash[:errors] = {message: "Could not delete manufacturer", title: "Manufacturer Not Deleted"}
        end
        
        redirect_to "/manufacturers"
    end

    def toggle_pmap
        mfn = Manufacturer.where("mfn_id = ? ", params[:id]).update(:has_pmap => params[:status])
        status = mfn.first.errors.blank? 
        respond_to do |format|
            format.json {render json: status}       
        end
    end

    private
    def mfn_params
        params.require(:manufacturer).permit(:voided,:mfn_id,:name, :has_pmap)
    end
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
    def pmap_options
        return Manufacturer.where(:has_pmap => true, :voided => false).count()
    end

    def pmap_suppliers
        return PmapInventory.select("distinct manufacturer").count()
    end
    def active_manufacturers
        return Manufacturer.where(:voided => false).count()
    end

end

app/views/manufacturers/_delete.html.erb
<%= form_for :manufacturer, :html => { :class => "form-horizontal general_inventory" }, :url => "/manufacturers/#{@manufacturer.id}", method: "delete"  do |f| %>
    <div class="card">
        <h5 class="card-header bg-secondary text-light">Cancel Prescription</h5>
        <div class="card-body">
            <div class="form-group row">
                <div class="col-md-12">
                    Are you sure you want to delete <%= @manufacturer.name %> as a manufacturer?
                </div>
            </div>
        </div>
        <div class="card-footer text-right">
            <button type="submit" class="btn btn-success">Yes</button>
            <button type="button" class="btn btn-danger" onMouseDown="hideModal()">No</button>
        </div>
    </div>
<% end %>

app/views/manufacturers/_edit.html.erb
<%= form_for :manufacturer, :url => "/manufacturers/update", :method => "PATCH"  do |f| %>
    <div class="card">
        <h5 class="card-header bg-dark text-light">Editing Manufacturer Details</h5>
        <div class="card-body">
            <div class="form-group row">
                <label for="itemName" class="col-md-10 col-form-label">Manufacturer Name</label>
                <div class="col-md-11">
                    <input type="text" class="form-control" value='<%= @manufacturer.name %>' placeholder="Enter Manufacturer Name" autocomplete="off" name="manufacturer[name]" required>
                </div>
            </div>
            <div class="form-group row">
                <label for="itemLotNumber" class="col-md-6 col-form-label">Manufacturer has PAP?</label>
                <div class="col-md-3">
                    <input class="form-check-input" type="radio" name="manufacturer[has_pmap]" <%= @manufacturer.has_pmap ? 'checked' : 'unchecked' %> id="gridRadios1" value="true" required>
                     <label class="form-check-label" for="gridRadios1">Yes</label>
                </div>
                <div class="col-md-3">
                    <input class="form-check-input" type="radio" name="manufacturer[has_pmap]" <%= !@manufacturer.has_pmap ? 'checked' : 'unchecked' %> id="gridRadios1" value="false" required>
                    <label class="form-check-label" for="gridRadios1">No</label>
                </div>
            </div>
        </div>
        <div class="card-footer text-right">
            <button type="submit" class="btn btn-lg btn-success">Submit</button>
            <button type="button" class="btn btn-lg btn-danger mr-2" onMouseDown="hideModal()">Close</button>
        </div>
    </div>
    <%= f.hidden_field :mfn_id, :value => @manufacturer.id %>
<% end %>

app/views/manufacturers/_new.html.erb
<%= form_for :manufacturer, :url => "/manufacturers"  do |f| %>
    <div class="card">
        <h5 class="card-header bg-dark text-light">Add New Manufacturer</h5>
        <div class="card-body">
            <div class="form-group row">
                <label for="itemName" class="col-md-10 col-form-label">Manufacturer Name</label>
                <div class="col-md-11">
                    <input type="text" class="form-control" placeholder="Enter Manufacturer Name" autocomplete="off" name="manufacturer[name]" required>
                </div>
            </div>
            <div class="form-group row align-middle">
                <label for="itemLotNumber" class="col-md-6 col-form-label">Manufacturer has PAP?</label>
                <div class="col-md-3">
                    <input class="form-check-input" type="radio" name="manufacturer[has_pmap]" id="gridRadios1" value="true" required>
                    <label class="form-check-label" for="gridRadios1">Yes</label>
                </div>
                <div class="col-md-3">
                    <input class="form-check-input" type="radio" name="manufacturer[has_pmap]" id="gridRadios1" value="false" required>
                    <label class="form-check-label" for="gridRadios1">No</label>
                </div>
            </div>
        </div>
        <div class="card-footer text-right">
            <button type="submit" class="btn btn-lg btn-success">Submit</button>
            <button type="button" class="btn btn-lg btn-danger mr-2" onMouseDown="hideModal()">Close</button>
        </div>
    </div>
<% end %>

app/views/manufacturers/index.html.erb
<link href=<%= asset_path("bootstrap4-toggle.min.css") %> rel="stylesheet">
<link rel="stylesheet" type="text/css" href=<%= asset_path("datatables.min.css") %> />
<script type="text/javascript" src=<%= asset_path("datatables.min.js") %>> </script>
<script src=<%= asset_path("bootstrap4-toggle.min.js") %>></script>

<!-- Modal -->
<div class="modal fade" id="appModal" tabindex="-1" aria-labelledby="appModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content" id="modalContent">
      test
    </div>
  </div>
</div> 

<div class="page-header" style="margin: 0px !important;padding: 0px !important;">
  <h3><%=t '.title', :default => "Manufacturers" %></h3>
</div>

<div class="row">
    <div class="col-10">
        <table id="manufacturers" class="table table-striped table-bordered" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th style="width: 3%;">#</th>
                    <th>Manufacturer</th>
                    <th style="width: 10%;">Has PAP</th>
                    <th style="width: 5%;">Actions</th>
                </tr>
            </thead>

            <tbody>
                <% i = 1 %>
                <% (@manufacturers || []).each do |manufacturer| %>
                    <tr>
                        <td><%= i %></td>
                        <td><%= manufacturer.name %></td>
                        <td>
                            <input type="checkbox" data-id="<%= manufacturer.id %>" data-on="Has PAP" data-off="No PAP" <%= manufacturer.has_pmap ? 'checked' : 'unchecked' %> data-toggle="toggle" data-offstyle="danger" data-onstyle="success">
                        </td>
                        <td>
                            <%= link_to image_tag('edit'), edit_manufacturer_path(manufacturer), remote: true %>                                    
                            <%= link_to image_tag('delete'), void_manufacturer_path(manufacturer), remote: true %>
                        </td>
                    </tr>
                    <% i += 1 %>
                <% end %>
            </tbody>
        </table>
    </div>
    <div class="col-2">
        <div class="card mb-3">
            <div class="card-header text-white bg-info text-center"><h5 class="card-title">Manufacturer Summary</h5></div>
            <div class="card-body ">
                <a href="/manufacturers" class="card text-center m-2 text-decoration-none">
                    <div class="card-body">
                    <h5 class="card-subtitle">Manufacturers</h5>
                    <p class="card-text"><%= active_manufacturers %></p>
                    </div>
                </a>
                <a href="/manufacturers?has_pmap=true" class="card text-center mt-3 m-1 text-decoration-none">
                    <div class="card-body">
                    <h5 class="card-subtitle">MFRs With PMAP</h5>
                    <p class="card-text"><%= pmap_options %></p>
                    </div>
                </a>
                <a href="/manufacturers?supports_us=true" class="card text-center mt-3 m-1 text-decoration-none">
                    <div class="card-body">
                    <h5 class="card-subtitle">Supporting Our Patients</h5>
                    <p class="card-text"><%= pmap_suppliers %></p>
                    </div>
                </a>
            </div>
        </div>
        <%= link_to '<button class="btn btn-primary btn-lg btn-block">Add Manufacturer</button>'.html_safe, new_manufacturer_path, remote: true %>        
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $('#manufacturers').DataTable({
            "pageLength": 9,
            "lengthChange": false        
            });
    } );


    function hideModal(){
        document.getElementById("appModal").style.display = "none"
        document.getElementById("appModal").classList.remove("show")

    }

    $(function() {
        $('input:checkbox').change(function(e) {
            $.ajax({
                url: '/toggle_pmap/' + $(this).attr("data-id"),
                type: 'POST',
                headers: { 'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content') },
                data: {'status': $(this).prop('checked')},
                success: function(data) {
                    console.log('success')
                },
                error: function() {
                    console.log('failure')
                }
            });
        })
    })
</script>